image:
  tag: 29.0.3

replicaCount: 1

service:
  type: LoadBalancer
  loadBalancerIP: 185.4.72.4

ingress:
  enabled: true
  hosts:
    - host: nc.bits.ee
      paths:
        - /

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  host: nextcloud-mysqlsrv.mysql.database.azure.com:3306
  database: nextcloud_db
  user: nextcloud_admin

persistence:
  enabled: true

nextcloud:
  host: nc.bits.ee
  phpConfigs:
    zzz-custom.ini: |-
      memory_limit=1G
      max_execution_time=180